version: '3'

services:

  front_end_server:
    build:
      context: ./front_end_server/
      dockerfile: Dockerfile
    command: ./front_end_server
    ports:
      - "8080:8080"
    env_file:
      - kafka.env
      - front_end_server/.env
    depends_on:
      - mongo
      - redis

  grpc_server:
    build:
      context:  ./grpc_server/
      dockerfile: Dockerfile
    command: ./grpc_server
    expose:
      - "4040"
    env_file:
      - kafka.env
      - grpc_server/.env
    depends_on:
      - broker

  matcher:
    build:
      context: ./matcher/
      dockerfile: Dockerfile
    command: ./matcher
    env_file:
      - kafka.env
      - matcher/.env
    depends_on:
      - broker

  redis:
    image: redis
    hostname: redis
    container_name: redis
    command: redis-server --requirepass redis_pass
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-enterprise-kafka:5.3.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: broker
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

# Might use later

#  schema-registry:
#    image: confluentinc/cp-schema-registry:5.3.0
#    hostname: schema-registry
#    container_name: schema-registry
#    depends_on:
#      - zookeeper
#      - broker
#    ports:
#      - "8081:8081"
#    environment:
#      SCHEMA_REGISTRY_HOST_NAME: schema-registry
#      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
#
#  rest-proxy:
#    image: confluentinc/cp-kafka-rest:5.3.0
#    depends_on:
#      - zookeeper
#      - broker
#      - schema-registry
#    ports:
#      - 8082:8082
#    hostname: rest-proxy
#    container_name: rest-proxy
#    environment:
#      KAFKA_REST_HOST_NAME: rest-proxy
#      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:29092'
#      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
